### ISSUE TITLE
无法加载游戏列表，以及从最小化恢复后UI显示有问题

### ISSUE THREAD

**Issue by omicronyang** [rmbadmin/SteamTools#1]
无法显示已安装的游戏列表（可能是因为我的游戏库不在steam安装位置而是在另外的硬盘新建了一个库？）
以及，程序从最小化恢复后，左侧和顶侧的窗体边框和阴影均向内漂移（拖动窗口后恢复正常）

**Comment by omicronyang** [comment]
![QQ图片20201218195151](https://user-images.githubusercontent.com/15993827/102611730-7f1edd00-416a-11eb-8e68-a619e3fbecb8.png)

**Comment by rmbadmin** [comment]
关于界面问题想问一下是否启用了系统dpi缩放，
游戏列表的话应该是不会受其它硬盘库影响的，
游戏列表加载不出来的时候有正确获取到Steam当前登录用户数据吗（可以查看托盘菜单是否显示了steam昵称和头像），
同时你试试能访问https://api.steampowered.com/ISteamApps/GetAppList/v2获取到游戏数据吗。

**Comment by omicronyang** [comment]
1. 确实启用了系统dpi缩放，150%
2. 托盘菜单和程序内起始页能显示steam昵称和头像，api可以获取到游戏列表

**Comment by rmbadmin** [comment]
最小化ui问题已经修复，
游戏列表加载问题可能是本地缓存文件在没有下载完成的情况下程序关闭所以缓存文件没有内容，刷新本地缓存或者删除apps.json文件重新下载可否解决？

**Comment by omicronyang** [comment]
缓存完毕后已经可以正确加载游戏列表，UI问题也解决了，感谢
