### ISSUE TITLE
Steam++ 进入后台之后，过一会就自动退出

### ISSUE THREAD

**Issue by govmoe** [rmbadmin/SteamTools#10]
steam++ 进入后台之后就经常自动退出，然后再手动打开，然后又自动退出了==

**Comment by rmbadmin** [comment]
请问新版本是否还有这个状况，已经修复了许多可能导致闪退的问题

**Comment by govmoe** [comment]
> 请问新版本是否还有这个状况，已经修复了许多可能导致闪退的问题

新版本打开就闪退了，或者根本打不开

**Comment by govmoe** [comment]
> 请问新版本是否还有这个状况，已经修复了许多可能导致闪退的问题

我试试，应该没问题了(?

**Comment by rmbadmin** [comment]
> > 请问新版本是否还有这个状况，已经修复了许多可能导致闪退的问题
> 
> 新版本打开就闪退了，或者根本打不开

是刚刚发布的1.0.5吗？
能不能提供一下windows日志里应用程序steam++的错误日志

**Comment by govmoe** [comment]
> > > 请问新版本是否还有这个状况，已经修复了许多可能导致闪退的问题
> > 
> > 
> > 新版本打开就闪退了，或者根本打不开
> 
> 是刚刚发布的1.0.5吗？
> 能不能提供一下windows日志里应用程序steam++的错误日志

抱歉啊，是1.0.4，我可能忘记更新了，没太注意刚刚发布的1.0.5

**Comment by rmbadmin** [comment]
没事，等后续在反馈一下1.0.5还会有问题吗

**Comment by govmoe** [comment]
好的:P

**Comment by govmoe** [comment]
1.0.5不会闪退崩溃了，正常了

**Comment by rmbadmin** [comment]
使用后过一段时间闪退的问题也没了吗？ 
没有问题的话我就关闭这个问题了

**Comment by govmoe** [comment]
> 使用后过一段时间闪退的问题也没了吗？
> 没有问题的话我就关闭这个问题了

没了~

**Comment by huangyucheni** [comment]
我的3.0.0rc9mac 也有这个问题

**Comment by Visitor5830** [comment]
和上一位朋友一样，我也是用mac运行的最新版本3.0.0-rc9，在加速一段时间后它就自动退出了。
