### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by gdf159159** [rmbadmin/SteamTools#12]
ios手机 我把SteamTools.Certificate.pfx证书安装到手机上信赖之后

把 steamcommunity.com 通过surge DNS映射 ip到电脑上

还是会提示我证书无效   浏览器忽略证书可以打开steamcommunity.com

大佬给否给我一份 这个工具可以在手机上用的ca根证书

**Comment by rmbadmin** [comment]
证书是随机生成的，之后会同时生成一份cer格式的证书
