### ISSUE TITLE
无法正常反代cdn.discordapp.com

### ISSUE THREAD

**Issue by silicer** [rmbadmin/SteamTools#13]
反代discord时，在网页上的部分图片（域名为[cdn.discordapp.com](https://cdn.discordapp.com)）无法加载，提示403 Forbidden，包括emoji和原图浏览，如

Emoji [https://cdn.discordapp.com/emojis/751617826086715453.png?v=1](https://cdn.discordapp.com/emojis/751617826086715453.png?v=1)

图片 [https://cdn.discordapp.com/attachments/605249075356368896/788950735630630952/FB_IMG_1606942366841.jpg](https://cdn.discordapp.com/attachments/605249075356368896/788950735630630952/FB_IMG_1606942366841.jpg)

同时客户端不能登录，同样显示403 Forbidden

**Comment by LemonPAKA** [comment]
（遇到了同样的情况，我甚至以为是我的问题）

**Comment by rmbadmin** [comment]
测试下1.0.4能正常吗？

**Comment by silicer** [comment]
非常感谢，已经可以正常使用了！
