### ISSUE TITLE
令牌页面会触发 ArgumentNullException

### ISSUE THREAD

**Issue by ad52825196** [rmbadmin/SteamTools#15]
第一次进入令牌页面，并没有添加令牌的情况下，可以点击编辑令牌按钮，点击以后再点击一次就会触发报错，同时程序退出。
![error](https://user-images.githubusercontent.com/4177837/103134767-7608af80-4718-11eb-93e0-60ed3e801e74.png)

**Comment by rmbadmin** [comment]
该问题下个版本会修复

**Comment by rmbadmin** [comment]
1.0.3已修复
