### ISSUE TITLE
本地令牌从WinAuth导入无效

### ISSUE THREAD

**Issue by zero617** [rmbadmin/SteamTools#21]
导入.txt文件后跳转到本地令牌界面 没有任何反应

https://user-images.githubusercontent.com/67105838/103162684-8448ef80-482e-11eb-8b0c-5d8bcb7fb869.mp4

**Comment by rmbadmin** [comment]
看起来是因为窗口被标签化了，所以展示错了窗口，导入过程选择txt文件后，还缺一步按下确认导入按钮

**Comment by zero617** [comment]
OK 解决了

**Comment by zero617** [comment]
解决了
