### ISSUE TITLE
这是什么原因，打开就这样，更新了也不行

### ISSUE THREAD

**Issue by Krisolthokaran** [rmbadmin/SteamTools#22]
![QQ截图20201227110954](https://user-images.githubusercontent.com/69186733/103163087-23241a80-4834-11eb-8eb8-cf51f14d7975.png)
如图

**Comment by rmbadmin** [comment]
更新到1.0.3.2是应该不会有这个问题的，已经修改了弹窗方式

**Comment by Krisolthokaran** [comment]
ok
