### ISSUE TITLE
通过托盘图标可打开数个相同的窗口，且无法关闭

### ISSUE THREAD

**Issue by luoboQuQ** [rmbadmin/SteamTools#23]
多次点击托盘图标，会弹出点击次数个相同的窗口。
通过窗口右上角的“×”只能关闭最新打开的那一个窗口，剩下的窗口将无法通过右上角的“×”关闭，只能通过任务管理器结束进程或在托盘图标右击菜单选退出才能关闭。
![图片](https://user-images.githubusercontent.com/60833237/103163968-11e10b00-4840-11eb-8963-f906e2c380e4.png)

**Comment by rmbadmin** [comment]
之后更新修复

**Comment by rmbadmin** [comment]
1.0.3.3更新修复
