### ISSUE TITLE
覆盖升级新版本导致令牌丢失

### ISSUE THREAD

**Issue by Mr54233** [rmbadmin/SteamTools#24]
刚收到1.0.3.3的升级，覆盖升级完之后发现令牌丢失
![image](https://user-images.githubusercontent.com/46802509/103168340-2ee00300-486d-11eb-8d09-de4518de97df.png)

**Comment by rmbadmin** [comment]
再次打开旧版本的话，令牌能加载出来吗？之后会出个令牌导出备份的功能避免这种情况

**Comment by Mr54233** [comment]
> 再次打开旧版本的话,令牌能加载出来吗?之后会出个令牌导出备份的功能避免这种情况

我。。我是覆盖升级啊qwq。印象中上次导入也是因为覆盖升级令牌消失的来着。

**Comment by rmbadmin** [comment]
你可以再下一个旧版本再试试，在我这测试的话，1.0.2以后存储的令牌都是能读取的，

 如果还有这种问题，目前可以尝试手动备份，令牌的存储路径在%localappdata%\rmbgame.net\SteamTools 

以后会支持令牌导出备份、
同时支持程序的配置文件保存路径设置和配置保存备份、
来多方面避免程序配置丢失的问题。

**Comment by Mr54233** [comment]
> 你可以再下一个旧版本再试试，在我这测试的话，1.0.2以后存储的令牌都是能读取的，
> 
> 如果还有这种问题，目前可以尝试手动备份，令牌的存储路径在%localappdata%\[rmbgame.net](http://rmbgame.net)\SteamTools
> 
> 以后会支持令牌导出备份、
> 同时支持程序的配置文件保存路径设置和配置保存备份、
> 来多方面避免程序配置丢失的问题。

1.0.2可以读取，换回新版本就读不出，奇了怪了

**Comment by rmbadmin** [comment]
我可能发现了问题，因为我移除了对令牌文件中的一个不必要的参数的写入读取，暂时只能麻烦通过查看令牌里的数据重新导入到1.0.3.3吧

**Comment by Mr54233** [comment]
> 我可能发现了问题，因为我移除了对令牌文件中的一个不必要的参数的写入读取，暂时只能麻烦通过查看令牌里的数据重新导入到1.0.3.3吧

好的，坐等大佬下个版本更新

**Comment by rmbadmin** [comment]
1.0.4应该已经修复

**Comment by Mr54233** [comment]
> 1.0.4应该已经修复

已更新，但更新之前还是丢失了一次令牌，更新完重新导入了。

另外更新完之后发现本地游戏库无法读取\读取缓慢？

![image](https://user-images.githubusercontent.com/46802509/103219678-56ac9500-4959-11eb-90c7-d3d4690df7f8.png)

有没有办法清空一下缓存重新读取一遍？

**Comment by rmbadmin** [comment]
删除程序根目录下的apps.json重新启动程序可以强制重新下载缓存，
1.0.4版本令牌保存这一块改动了许多，所以是不会支持读取之前版本的令牌

**Comment by rmbadmin** [comment]
1.0.5版本发布了，你可以再试试覆盖升级是否会重置令牌，如果没有问题了就准备关闭此问题

**Comment by Mr54233** [comment]
> 1.0.5版本发布了，你可以再试试覆盖升级是否会重置令牌，如果没有问题了就准备关闭此问题

刚更新完，没有问题，感谢大佬
