### ISSUE TITLE
更新到1.0.3.3后需要验证登录信息

### ISSUE THREAD

**Issue by GOD2333** [rmbadmin/SteamTools#25]
![image](https://user-images.githubusercontent.com/38485808/103169977-7a99a900-487b-11eb-825e-632c7d9d240a.png)
点登录后会提示"在连接至 Steam 服务器时发生了一个错误。请稍后重试。"
试过换回1.0.2是正常显示

**Comment by rmbadmin** [comment]
在我这测试是可以正常登陆的，能告知一下cmd执行命令ping steampowered.com命令返回的ip地址吗

**Comment by GOD2333** [comment]
104.103.230.109

**Comment by GOD2333** [comment]
正在 Ping steampowered.com [104.103.230.109] 具有 32 字节的数据:
来自 104.103.230.109 的回复: 字节=32 时间=218ms TTL=51
来自 104.103.230.109 的回复: 字节=32 时间=199ms TTL=51
来自 104.103.230.109 的回复: 字节=32 时间=210ms TTL=51
来自 104.103.230.109 的回复: 字节=32 时间=231ms TTL=51

正在 Ping steampowered.com [23.35.112.59] 具有 32 字节的数据:
请求超时。
请求超时。
来自 23.35.112.59 的回复: 字节=32 时间=277ms TTL=51
来自 23.35.112.59 的回复: 字节=32 时间=260ms TTL=51

重新ping后ip变了

**Comment by LemonPAKA** [comment]
> 正在 Ping steampowered.com [104.103.230.109] 具有 32 字节的数据:
> 来自 104.103.230.109 的回复: 字节=32 时间=218ms TTL=51
> 来自 104.103.230.109 的回复: 字节=32 时间=199ms TTL=51
> 来自 104.103.230.109 的回复: 字节=32 时间=210ms TTL=51
> 来自 104.103.230.109 的回复: 字节=32 时间=231ms TTL=51
> 
> 正在 Ping steampowered.com [23.35.112.59] 具有 32 字节的数据:
> 请求超时。
> 请求超时。
> 来自 23.35.112.59 的回复: 字节=32 时间=277ms TTL=51
> 来自 23.35.112.59 的回复: 字节=32 时间=260ms TTL=51
> 
> 重新ping后ip变了

有可能是开了加速器的问题。。。也有可能单纯是DNS解析抽风之类的

**Comment by rmbadmin** [comment]
已发现问题，之后更新修复

**Comment by rmbadmin** [comment]
1.0.4应该已经修复

**Comment by GOD2333** [comment]
多谢大佬,1.0.4没有问题了
