### ISSUE TITLE
用了几天之后打开报错  

### ISSUE THREAD

**Issue by Suercx** [rmbadmin/SteamTools#28]
System.InvalidOperationException: 无法将 Owner 属性设置为之前未显示的 Window。

   在 System.Windows.Window.set_Owner(Window value)

   在 Livet.Behaviors.Messaging.TransitionInteractionMessageAction.InvokeAction(InteractionMessage message)

   在 Livet.Behaviors.Messaging.InteractionMessageAction`1.Invoke(Object parameter)

   在 Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter)

   在 Livet.Behaviors.Messaging.InteractionMessageTrigger.<>c__DisplayClass21_0.<MessageReceived>b__1()

   在 Livet.Behaviors.Messaging.InteractionMessageTrigger.DoActionOnDispatcher(Action action)

   在 Livet.Behaviors.Messaging.InteractionMessageTrigger.MessageReceived(Object sender, InteractionMessageRaisedEventArgs e)

   在 Livet.EventListeners.WeakEvents.LivetWeakEventListener`2.ReceiveEvent(WeakReference`1 listenerWeakReference, Object sender, TEventArgs args)

   在 Livet.EventListeners.WeakEvents.LivetWeakEventListener`2.<>c__DisplayClass9_0.<GetStaticHandler>b__0(Object sender, TEventArgs e)

   在 System.EventHandler`1.Invoke(Object sender, TEventArgs e)

   在 Livet.Messaging.InteractionMessenger.Raise(InteractionMessage message)

   在 MetroTrilithon.Mvvm.WindowViewModel.Transition(ViewModel viewModel, Type windowType, TransitionMode mode, Boolean isOwned)

   在 SteamTools.ViewModels.MainWindowViewModelBase.Dialog(String content, String title)

   在 SteamTools.Services.AutoUpdateService.<CheckUpdate>d__8.MoveNext()

--- 引发异常的上一位置中堆栈跟踪的末尾 ---

   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------

**Comment by rmbadmin** [comment]
用的是最新的1.0.4吗？ 1.0.4在更新阶段已经没有弹窗了 应该不会出现这种错误了

**Comment by rmbadmin** [comment]
你好，麻烦测试一下1.0.5还会有这个问题吗，如果没问题的话我就要关闭这个问题了

**Comment by Suercx** [comment]
没问题了  是我版本太久了   谢谢大佬
