### ISSUE TITLE
加速状态下影响守望先锋

### ISSUE THREAD

**Issue by someash** [rmbadmin/SteamTools#30]
加速情况下守望先锋打不开

**Comment by rmbadmin** [comment]
能否详细描述一下启用了哪些代理服务，守望先锋是国服还是国际服，启动后打不开的反应是出错还是没有任何反应，观察下任务管理器能否看到守望先锋进程出现？

在我本机测试是可以启动加速后正常启动守望先锋（国服）的。

**Comment by someash** [comment]
我只加速了steam图片和社区，之前有连续两次出错，都是关掉加速就好了，所以发了这个issue，不过今天上ow的时候却没有出错，我再观察一段时间看能否复现

**Comment by someash** [comment]
几天的使用没有再复现这个bug，所以先关了吧
