### ISSUE TITLE
库存游戏列表显示为空，或许是因为我把游戏全部放到了别的地方？

### ISSUE THREAD

**Issue by ZYFDroid** [rmbadmin/SteamTools#33]

**Comment by ZYFDroid** [comment]
![图片](https://user-images.githubusercontent.com/39429452/103784232-a9caca00-5074-11eb-8b8f-9526d23e860a.png)
![图片](https://user-images.githubusercontent.com/39429452/103784285-bb13d680-5074-11eb-9910-10d3bbbc13b1.png)

**Comment by rmbadmin** [comment]
看一下程序根目录下的apps.json文件是不是没内容或者内容不完整，可能是网络访问[Steam API](https://api.steampowered.com/ISteamApps/GetAppList/v2)过慢，可以试试手动打开这个链接然后保存为文件apps.json放到程序根目录下覆盖。

**Comment by ZYFDroid** [comment]
问题解决了
