### ISSUE TITLE
使用一周后无法再次打开

### ISSUE THREAD

**Issue by CrazyDoge666** [rmbadmin/SteamTools#35]
处理器	Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz   3.70 GHz
机带 RAM	16.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎12/‎14
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0
Steam++1.0.4与1.0.5都试过一样的报错
![image](https://user-images.githubusercontent.com/36259181/103974604-11af0c80-516a-11eb-9e75-5c613aa9237e.png)

**Comment by rmbadmin** [comment]
检查hosts文件是否乱码或者内容超过了500MB以上，手动清空一下，再重启steam++

**Comment by rmbadmin** [comment]
出现这个问题的原因我确实暂时还不知道，只是有人反馈了所以发现了这个问题，希望能留意到是如何出现这个BUG的，比如与什么其它改hosts软件冲突了。
我自己确实没有出现过这个问题。

**Comment by CrazyDoge666** [comment]
> 检查主机文件是否乱码或内容超过了500MB以上，手动清空一下，再重启steam ++
已解决，感谢

**Comment by ZYFDroid** [comment]
我也遇到了这个bug，在使用几天后，当我尝试启动steam时，程序就会崩溃。
我试着使用VisualStudio附加到进程，得到了下面的调试信息
System.ArgumentNullException
  HResult=0x80004003
  Message=值不能为 null。
Arg_ParamName_Name
  Source=Newtonsoft.Json
  StackTrace:
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 SteamTool.Steam.Service.Web.SteamDbApiService.<GetUserInfo>d__1.MoveNext()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamTools.Services.SteamConnectService.<<Initialize>b__22_0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

![图片](https://user-images.githubusercontent.com/39429452/104001571-d00a7a00-51da-11eb-8848-a6141e128009.png)

**Comment by ZYFDroid** [comment]
> 
> 
> 我也遇到了这个bug，在使用几天后，当我尝试启动steam时，程序就会崩溃。
> 我试着使用VisualStudio附加到进程，得到了下面的调试信息
> System.ArgumentNullException
> HResult=0x80004003
> Message=值不能为 null。
> Arg_ParamName_Name
> Source=Newtonsoft.Json
> StackTrace:
> 在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
> 在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
> 在 SteamTool.Steam.Service.Web.SteamDbApiService.d__1.MoveNext()
> 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 在 SteamTools.Services.SteamConnectService.<b__22_0>d.MoveNext()
> 在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_1(Object state)
> 在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
> 在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> 在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
> 在 System.Threading.ThreadPoolWorkQueue.Dispatch()
> 在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> 
> 此异常最初是在此调用堆栈中引发的:
> [外部代码]
> 
> ![图片](https://user-images.githubusercontent.com/39429452/104001571-d00a7a00-51da-11eb-8848-a6141e128009.png)

更新到1.0.5之后问题消失了

**Comment by H0wAway** [comment]
> 检查主机文件是否乱码或内容超过了500MB以上，手动清空一下，再重启steam ++

是的，是这个问题。我的hosts文件只有335MB，同样的报错。清空之后就能正常使用。
