### ISSUE TITLE
开机自启报错

### ISSUE THREAD

**Issue by LemonPAKA** [rmbadmin/SteamTools#36]
开机自启报错
![QQ截图20210108165359](https://user-images.githubusercontent.com/17202894/103994728-500af280-518f-11eb-926d-c975fdf027a3.png)
报错后不会闪退，进入软件后令牌消失并且窗体主题颜色变回默认
![QQ截图20210108165417](https://user-images.githubusercontent.com/17202894/103994790-66b14980-518f-11eb-8701-42e0fe737c75.png)
右下角角标右键背景色变黑
![QQ截图20210108165435](https://user-images.githubusercontent.com/17202894/103994815-70d34800-518f-11eb-849e-82ef25f25ec1.png)
如果立刻关闭后再次启动，有概率正常启动，有概率报以下错误
![QQ截图20210108165502](https://user-images.githubusercontent.com/17202894/103995105-e0e1ce00-518f-11eb-8b60-2da2c4992a57.png)

**Comment by rmbadmin** [comment]
测试一下1.0.6版本吧

**Comment by LemonPAKA** [comment]
> 测试一下1.0.6版本吧

试了下，没报错了应该没事了，有问题我再开新的issue了
