### ISSUE TITLE
Twitch没法看视频

### ISSUE THREAD

**Issue by YogurtZebra** [rmbadmin/SteamTools#38]
网页能正常登录与打开，但是视频和直播都看不了
是否是因为sni阻断的缘故？
![image](https://user-images.githubusercontent.com/57581480/104089867-4081cb80-52ad-11eb-9a0d-7716361278cc.png)

**Comment by YogurtZebra** [comment]
其他的代理像Github和Pixiv都是正常的

**Comment by rmbadmin** [comment]
下个版本将会修复

**Comment by rmbadmin** [comment]
测试一下1.0.6能否正常访问

**Comment by YogurtZebra** [comment]
> 测试一下1.0.6能否正常访问

可以正常访问，速度也还行
