### ISSUE TITLE
设置开机自启也不会自启，而且每次打开代理列表都会还原还需要再次收到勾选

### ISSUE THREAD

**Issue by heibaigame** [rmbadmin/SteamTools#39]
设置开机自启也不会自启，而且每次打开代理列表都会还原还需要再次收到勾选
<a href="https://sm.ms/image/7meruqhKIAPR3WN" target="_blank"><img src="https://i.loli.net/2021/01/11/7meruqhKIAPR3WN.jpg" ></a>

**Comment by rmbadmin** [comment]
可以检查下路径 %HOMEPATH%\AppData\Local\rmbgame.net\Steam++目录下的配置文件是否正常存储了配置数据，然后尝试重新启动steam++设置时文件是否有正确修改，如果没有的话反馈一下错误的配置文件

**Comment by heibaigame** [comment]
重新配制一下正常了
