### ISSUE TITLE
本地令牌功能报错

### ISSUE THREAD

**Issue by LemonPAKA** [rmbadmin/SteamTools#4]
![QQ图片20201220024441](https://user-images.githubusercontent.com/17202894/102697011-6fff6400-422a-11eb-9cba-8f8b18c48c98.png)
![本地令牌报错](https://user-images.githubusercontent.com/17202894/102697013-7261be00-422a-11eb-991f-b369707f727d.png)
已经添加过令牌文件，不知道为何之前能用，现在不显示了，点编辑或者重新添加都会报错

**Comment by rmbadmin** [comment]
这个问题我已经发现并修复了，等下个版本更新吧，不好意思，我会很快推出一个修复BUG的稳定版本先

**Comment by LemonPAKA** [comment]
> 这个问题我已经发现并修复了，等下个版本更新吧，不好意思，我会很快推出一个修复BUG的稳定版本先

（有点好奇我是怎么触发的，然后现在又好了。。。还有貌似开UU加速STEAM社区的话会冲突闪退）

**Comment by rmbadmin** [comment]
原因的话其实是加载顺序问题，令牌初始化的时候跑到设置读取令牌文件数据之前去了，所以没读取到令牌抛出了null异常

uu加速steam社区冲突闪退我没有测试出来

**Comment by LemonPAKA** [comment]
> 原因的话其实是加载顺序问题，令牌初始化的时候跑到设置读取令牌文件数据之前去了，所以没读取到令牌抛出了null异常
> 
> uu加速steam社区冲突闪退我没有测试出来

可能是hosts占用的问题。。。加速器貌似某个模式会改hosts
