### ISSUE TITLE
导出旧版令牌在哪呀

### ISSUE THREAD

**Issue by Startear187** [rmbadmin/SteamTools#43]
104更新新版，但也加载不出旧版，103也没导出的选项

**Comment by rmbadmin** [comment]
设置里令牌设置，读取并导入旧版本数据

**Comment by Startear187** [comment]
那app导入方式咋导入不了了

**Comment by Startear187** [comment]
> 设置里令牌设置，读取并导入旧版本数据。
> 导出的话是在1.0.4才新出的功能，在这之前是没有的

那app介绍方式咋引进不了了

**Comment by rmbadmin** [comment]
可以手动到 路径%HOMEPATH%\AppData\Local\rmbgame.net\Steam++，检查下settings.json文件内是否有令牌数据AuthSettings.Authenticators

有的话可以将其复制出来在程序根目录下新建为authenticators.dat，然后在设置里打开令牌保存于程序根目录下

**Comment by Startear187** [comment]
> 可以手动到 路径%HOMEPATH%\AppData\Local\rmbgame.net\Steam++，检查下settings.json文件内是否有令牌数据AuthSettings.Authenticators
> 
> 有的话可以将其复制出来在程序根目录下新建为authenticators.dat，然后在设置里打开令牌保存于程序根目录下

欧克克，完美导入，谢谢，好工具
