### ISSUE TITLE
成就解锁出现错误然后闪退(调用的目标发生异常)

### ISSUE THREAD

**Issue by WilsonZhang041220** [rmbadmin/SteamTools#44]
<img width="724" alt="steampp_bug" src="https://user-images.githubusercontent.com/65215447/104540335-3a4b7080-565a-11eb-8f72-eb3e3c2cda8f.png">

**Comment by rmbadmin** [comment]
貌似因为程序没法正确获取自身所在的路径？，能详细说明下使用环境吗，以及查看下 任务管理器-详细信息-steam++.exe进程的命令行参数路径是否正确？

**Comment by WilsonZhang041220** [comment]
> 貌似因为程序没法正确获取自身所在的路径？，能详细说明下使用环境吗，以及查看下 任务管理器-详细信息-steam++.exe进程的命令行参数路径是否正确？

系统是win10 1909，steam++储存在D:\Steam\Steam++，用cmd提取命令行参数出现这
![image](https://user-images.githubusercontent.com/65215447/104667267-a5f01500-5710-11eb-8d1c-a4acbc19ac56.png)
但程序路径是对的
