### ISSUE TITLE
加速后社区依旧打不开

### ISSUE THREAD

**Issue by Krisolthokaran** [rmbadmin/SteamTools#51]
显示-324

**Comment by Krisolthokaran** [comment]
商店也一样

**Comment by rmbadmin** [comment]
可以测试一下其它代理的网站能否正常访问，如果是只有stema相关的无法访问，检查一下能否正常访问akamai的域名和ip
如果都无法访问，可以检查下443端口是否有被程序占用，是否正常启用了代理

**Comment by Krisolthokaran** [comment]
我人傻了，占用端口的就是steam++，退了重进没任何毛病了，不知道是什么原因

**Comment by rmbadmin** [comment]
可以在设置中启用程序的日志记录，然后问题再次出现时观察一下记录
