### ISSUE TITLE
Github头像加载问题以及Steam客户端无法登陆

### ISSUE THREAD

**Issue by YogurtZebra** [rmbadmin/SteamTools#53]
如图所示
![image](https://user-images.githubusercontent.com/57581480/105443213-1ca78800-5ca6-11eb-92bb-26e1e2d7fc81.png)
![image](https://user-images.githubusercontent.com/57581480/105443299-55476180-5ca6-11eb-9f5d-a1726284364d.png)

版本：1.0.6

**Comment by rmbadmin** [comment]
今天我也发现了，正在观察问题中

**Comment by rmbadmin** [comment]
目前相关问题还有pixiv的图片无法加载

**Comment by rmbadmin** [comment]
这里提问一下steam登录的这个问题应该与程序无关？
程序只是在本地电脑代理了，依然是各自网络直连g胖的，没有经过代理服务器中转。

**Comment by YogurtZebra** [comment]
> 这里提问一下steam登录的这个问题应该与程序无关？
> 程序只是在本地电脑代理了，依然是各自网络直连g胖的，没有经过代理服务器中转。

具体的原因不太清楚，但是网页端可以正常登录

**Comment by rmbadmin** [comment]
已经更新修复了github头像的问题了，steam登录再三排查应该不是steam++导致的，所以问题关闭。
