### ISSUE TITLE
启动和退出时出现异常

### ISSUE THREAD

**Issue by zhanghua000** [rmbadmin/SteamTools#54]
启动时异常如下：
![image](https://user-images.githubusercontent.com/17194552/105571938-ec87e400-5d8e-11eb-9887-b8886dea7e35.png)
并且启动后所有设置和令牌均丢失
退出时异常如下
![image](https://user-images.githubusercontent.com/17194552/105571971-383a8d80-5d8f-11eb-87c1-47c75fb178ee.png)
退出是在通知栏图标的右键菜单里面退出
求dalao解决一下

**Comment by rmbadmin** [comment]
关于这个问题我会尝试解决，不过我没法测试，可以加下我的steam或者qq帮我测试下修改后的版本能否解决问题

**Comment by zhanghua000** [comment]
dalao，我用 [已编辑] 这个Steam账号加了你的好友，已经发申请了

**Comment by zhanghua000** [comment]
刚刚又看了一下，似乎是我的443端口被VMware占用导致的，关闭VMware的共享虚拟机之后似乎就正常了，设置和令牌什么的都没有丢

**Comment by rmbadmin** [comment]
嗯，vmware的共享虚拟机功能会占用443端口，可以设置一个别的端口或者关闭这个功能

**Comment by zhanghua000** [comment]
所以dalao能在程序里面加一个提示吗？像steamcommunity 302一样，检查到端口被占用就给一个提示，给一个解决的方向，先谢谢dalao

**Comment by rmbadmin** [comment]
其实之前是有这个提示的，但是遇到了些问题暂时去除了，之后会在加回来的。

**Comment by zhanghua000** [comment]
懂了。不管怎么说，感谢dalao搞出这么有用的工具，这个issue我就关了
