### ISSUE TITLE
程序内自动更新出错

### ISSUE THREAD

**Issue by YogurtZebra** [rmbadmin/SteamTools#56]
报错
![image](https://user-images.githubusercontent.com/57581480/105627401-c9823080-5e71-11eb-9438-0bf6cd66774c.png)
点击确定后程序无响应并奔溃，重新打开仍为旧版本

**Comment by rmbadmin** [comment]
可能是升级的包没下载完吧，1.1版本之后加了效验了，没下载完不会在解压了
