### ISSUE TITLE
本地令牌相关问题

### ISSUE THREAD

**Issue by czv22** [rmbadmin/SteamTools#57]
手机已root，一步步按照教程搞得，但是却说导入失败，请确认数据是否准确
搞定了，是我理解能力有问题，抱歉
不过教程改成 打开“Steamguard——xxxxxxxxxxxx”这个文件并粘贴所有内容个人认为更好

**Comment by rmbadmin** [comment]
ok，会把这个教程文本改的更详细一点的，感谢反馈
