### ISSUE TITLE
导入的脚本不会记住上次勾选的状态

### ISSUE THREAD

**Issue by Zzzhou-Sco** [rmbadmin/SteamTools#67]
导入的脚本本次勾选启用后，下一次进入程序又要重新勾选，不会记住上次勾选的状态

**Comment by rmbadmin** [comment]
这个，我确实没还没有做勾选状态的保存，现在要修改的话，可以手动修改下脚本文件user script里的enable true/false。这一行，如果没有这一行可以添加
