### ISSUE TITLE
Windows 安全中心报毒

### ISSUE THREAD

**Issue by drrrMikado** [rmbadmin/SteamTools#68]
如图：
安全中心截图：
![image](https://user-images.githubusercontent.com/11224565/106759616-edadf080-666d-11eb-8e25-4029d61acaf9.png)
Chromium Edge 无法下载截图：
![image](https://user-images.githubusercontent.com/11224565/106759624-f0104a80-666d-11eb-9524-0a4ffa5b06a6.png)

目前通过加入白名单解决了，现在把信息提供下开发者，看看能不能解决下

**Comment by rmbadmin** [comment]
把EXE提交给微软是可以解除的，但是只有一个版本生效，下个版本新发布，可能又会报毒，又要重新提交微软验证。😂

**Comment by drrrMikado** [comment]
> 把EXE提交给微软是可以解除的，但是只有一个版本生效，下个版本新发布，可能又会报毒，又要重新提交微软验证。😂

啊，那只能每次发布 release 前提交验证了？

**Comment by rmbadmin** [comment]
> > 把EXE提交给微软是可以解除的，但是只有一个版本生效，下个版本新发布，可能又会报毒，又要重新提交微软验证。😂
> 
> 啊，那只能每次发布 release 前提交验证了？

是的，之后发布时我都尽量也提交验证。

**Comment by drrrMikado** [comment]
> 是的，之后发布时我都尽量也提交验证。

辛苦开发者了

**Comment by rmbadmin** [comment]
我已经提交了验证并且微软审核通过了，1.1.2版本应该不会在报毒了。
