### ISSUE TITLE
无法开机自启动

### ISSUE THREAD

**Issue by Laplacence** [rmbadmin/SteamTools#7]
在设置中开启后，该工具无法跟随系统自动启动。

**Comment by rmbadmin** [comment]
你可以查看一下windows管理里的任务计划程序库是否正确设置了steam++的启动计划和查找一下任务计划启动的历史记录。

**Comment by gdf159159** [comment]
win10 2009下也同样的问题 任务计划中  没有成功添加开机启动在任务计划中

**Comment by Laplacence** [comment]
Windows version 20H2
Build 19042.685
task里面有该任务，但是有错误
0x80070002

**Comment by Laplacence** [comment]
楼上的错误为，未找到路径。
然后我发现是我更改了文件路径，重新设置了一次恢复了。
最好把文件路径放到环境变量内，这样可以随意移动。
