### ISSUE TITLE
建议将生成的反代证书放置在根目录下

### ISSUE THREAD

**Issue by ccboxes** [rmbadmin/SteamTools#8]
如题，现在的证书没有办法导入到firefox等使用单独证书库的软件中。

**Comment by rmbadmin** [comment]
生成的反代证书已经在程序根目录下了，文件名为SteamTools.Certificate.pfx 密码为空

**Comment by ccboxes** [comment]
> 
> 
> 生成的反代证书已经在程序根目录下了，文件名为SteamTools.Certificate.pfx 密码为空

没错，但是这种带私钥的证书不能直接导入，必须转换成只有证书颁发机构的.cer或者.p7b才能导入。考虑兼容性的话.cer会更好。

**Comment by rmbadmin** [comment]
> > 生成的反代证书已经在程序根目录下了，文件名为SteamTools.Certificate.pfx 密码为空
> 
> 没错，但是这种带私钥的证书不能直接导入，必须转换成只有证书颁发机构的.cer或者.p7b才能导入。考虑兼容性的话.cer会更好。 @rmbadmin

好的吧，之后也做个生成一份cer证书到根目录，现在的pfx证书是没有密码的，所以如果急用可以自己用openssl转换一下pfx到cer或者使用widnows的证书导出也可以导出一份cer证书文件

**Comment by rmbadmin** [comment]
1.0.5已经添加生成证书同时生成一份cer文件在程序根目录，可能需要手动删除1.0.4之前的证书文件重新用1.0.5生成一下，你试试新生成的cer可以解决吗，如果没有问题就准备关闭这个问题了

**Comment by ccboxes** [comment]
> 1.0.5已经添加生成证书同时生成一份cer文件在程序根目录，可能需要手动删除1.0.4之前的证书文件重新用1.0.5生成一下，你试试新生成的cer可以解决吗，如果没有问题就准备关闭这个问题了

@rmbadmin 不行，从windows证书存储中导出的cer文件可以导入firefox，但是自动生成的不行。附上两份文件。

[证书.zip](https://github.com/rmbadmin/SteamTools/files/5785734/default.zip)

**Comment by rmbadmin** [comment]
> > 1.0.5已经添加生成证书同时生成一份cer文件在程序根目录，可能需要手动删除1.0.4之前的证书文件重新用1.0.5生成一下，你试试新生成的cer可以解决吗，如果没有问题就准备关闭这个问题了
> 
> @rmbadmin 不行，从windows证书存储中导出的cer文件可以导入firefox，但是自动生成的不行。附上两份文件。
> 
> [证书.zip](https://github.com/rmbadmin/SteamTools/files/5785734/default.zip)

我分析了一下，找到了问题原因，主要是文件的编码格式用的是utf8有bom的格式 然后火狐识别不了，之后修改成生成utf8无bom应该就可以了。

**Comment by rmbadmin** [comment]
最新发布的1.0.6版本麻烦在测试一下

**Comment by ccboxes** [comment]
@rmbadmin 已经可以正常导入，非常感谢

**Comment by swift-lee** [comment]
![image](https://user-images.githubusercontent.com/57428138/120443096-e4812600-c3b8-11eb-8db2-6b3c1b7edf2c.png)
要是能在这加一个导入火狐的快捷方式或者教程就好了，我是折腾了半天才想起来来查issue才翻到这里
